server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: admin
  redis:
    host: localhost
  rabbitmq:
    host: localhost
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

server.servlet.context-path: